
# Test nota doppia a corredo 1
# Test nota doppia a corredo 2
SENDER=Il mio conto\n \u00e8 sicuro?chi lo sa ?
RECIPIENT=Destinatario
# Test nota singola a corredo
THIRD_PARTY=Terze parti

! Test nota isola

CREDIT_CARD=Solo carta di credito \u00a9
COLLECT=Raccogliere \\\n (Solo per account di terra autorizzati)