
# Test nota doppia a corredo 1
# Test nota doppia a corredo 2
SENDER=Mon compte\n est-ce s\u00fbr ? Qui sait ?
RECIPIENT=Destinataire
# Test nota singola a corredo
THIRD_PARTY=Tiers

! Test nota isola

CREDIT_CARD=Carte de cr\u00e9dit uniquement \u00a9
COLLECT=Collecter \\\n (Comptes terrestres autoris\u00e9s uniquement)