
# Test nota doppia a corredo 1
# Test nota doppia a corredo 2
SENDER=Mon compte\n est-ce sans danger ?Qui sait ?
RECIPIENT=Destinataire
# Test nota singola a corredo
THIRD_PARTY=Tiers\tCiao !

! Test nota isola

CREDIT_CARD=Carte de crédit uniquement ©
COLLECT=Collecter \
(Comptes terrestres autorisés uniquement) \
Deuxième ligne multiligne