
# Test nota doppia a corredo 1
# Test nota doppia a corredo 2
SENDER=My account \r\n is safe ? \t who knows ?
RECIPIENT \ \ Recipient
# Test nota singola a corredo
THIRD_PARTY:Third Party

! Test nota isola

CREDIT_CARD   =    Credit Card only \u00A9
COLLECT=Collect \
(Authorized Ground Accounts only)